### GET all drivers

GET http://localhost:4444/api/drivers
Content-Type: application/json

### GET one driver
GET http://localhost:4444/api/drivers/25
Content-Type: application/json

### POST driver
POST http://localhost:4444/api/drivers
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "nationality": "Americana",
    "number": 25,
    "rookie": false,
    "teamId": 16
}

### UPDATE driver
PUT http://localhost:4444/api/drivers/25
Content-Type: application/json

{
    "firstName": "Oscar",
    "lastName": "Piastri",
    "nationality": "Australian",
    "number": 81,
    "rookie": false,
    "teamId": 13
}

### DELETE driver
DELETE http://localhost:4444/api/drivers/45
Content-Type: application/json
